name: guided_sd15

params:
  do_cfg: true
  cfg_scale: 7.5
  sampler_name: ddpm
  n_inference_steps: 30


assets:
  sd_repo_id: stable-diffusion-v1-5/stable-diffusion-v1-5
  sd_ckpt: v1-5-pruned-emaonly.ckpt
  clip_repo_id: openai/clip-vit-large-patch14
  vocab_file: vocab.json
  merges_file: merges.txt


guidance: 
  steps_to_guide: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  target_yes: true
  do_grad_checkpointing: true


optimizer:
  _target_: torch.optim.SGD
  lr: 0.1
  

logging:
  save_intermediate_finals: true
  save_guidance_diffs: true
  save_latents: false
  save_nablas: true
  save_yes_no_distributions: true


